---
# tasks file for find_vulnerabilities
- name:               Look for suspicious files
  find:
    path:             "{{ search_path | default('/var/www') }}"
    recurse:          yes
    follow:           yes
    file_type:        file
    hidden:           yes
    contains:         '(passthru|exec|eval|shell_exec|assert|str_rot13|system|phpinfo|base64_decode|chmod|mkdir|fopen|fclose|readfile)'
  register:           suspicious_files

- name:               Look for recently created files
  find:
    path:             "{{ search_path | default('/var/www') }}"
    recurse:          yes
    follow:           yes
    file_type:        file
    age:              "{{ file_age | default('-7d') }}"
  register:           recently_created_files

- name:               Make sure ssh politics are configured
  lineinfile:
    path:             /etc/ssh/sshd_config
    state:            present
    line:             "{{ item.line }}"
    regexp:           "{{ item.regexp }}"
  with_items:         "{{ sshd_config_lines }}"
  check_mode:         yes
  register:           ssh_configurations

- name:               Close ports 80-100
  firewalld:
    port:             "{{ item|int }}/tcp"
    permanent:        yes
    immediate:        yes
    state:            disabled
  with_sequence:      start=81 end=100
  check_mode:         yes
  register:           open_ports
